import type { Metadata } from "next";

import WhatsAppBadge from "@/components/WhatsAppBadge";
import { satoshiFont } from "@/shared/theme";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshiFont.className}`}>
        {children}
        <WhatsAppBadge />
      </body>
    </html>
  );
}
